name: Typescript

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - name: checkout repositry
      - uses: actions/checkout@v4

      - name: install 
        run: npm install

      - name: eslint
        run: npm run lint

      - name: test
        run: npm run test


