name: TypeScript

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --force

      - name: Test
        run: npx jest
      
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: path/to/test-results

